version: '3.9'

services:
  bot:
    build: '.'
    depends_on:
      - 'database'
    volumes:
      - './config.json:/usr/src/app/config.json'
      - './.env:/usr/src/app/.env'

  database:
    image: 'mongo'
    volumes:
      - 'mongodb_data:/data/db'

volumes:
  mongodb_data:
